// AUTO-GENERATED by scripts/generate-facade.ts — do not edit by hand.
// Regenerate with: pnpm --filter ableton-osc-bridge generate
import type { OscArg, Subscription, VerbProvider } from "../transport";

const num = (a: OscArg[], i: number): number => Number(a[i]);
const str = (a: OscArg[], i: number): string => String(a[i]);
const bool = (a: OscArg[], i: number): boolean => Number(a[i]) === 1;
const nums = (a: OscArg[], i: number): number[] => a.slice(i).map(Number);
const strs = (a: OscArg[], i: number): string[] => a.slice(i).map(String);


export class Application {
  constructor(private p: VerbProvider) {}
  /** Live version (major, minor) · OSC `/live/application/{get,set}/version` */
  get version() {
    const p = this.p; const id: OscArg[] = [];
    return {
      get: (timeoutMs?: number): Promise<string> => p.query("/live/application/get/version", id, timeoutMs).then((a) => str(a, 0)),
    };
  }
}

export class Song {
  constructor(private p: VerbProvider) {}
  /** Start session playback · OSC `/live/song/start_playing` */
  startPlaying(): void {
    const id: OscArg[] = [];
    this.p.send("/live/song/start_playing", [...id]);
  }

  /** Stop session playback · OSC `/live/song/stop_playing` */
  stopPlaying(): void {
    const id: OscArg[] = [];
    this.p.send("/live/song/stop_playing", [...id]);
  }

  /** Resume session playback · OSC `/live/song/continue_playing` */
  continuePlaying(): void {
    const id: OscArg[] = [];
    this.p.send("/live/song/continue_playing", [...id]);
  }

  /** Stop all clips from playing · OSC `/live/song/stop_all_clips` */
  stopAllClips(): void {
    const id: OscArg[] = [];
    this.p.send("/live/song/stop_all_clips", [...id]);
  }

  /** Mimic a tap of Tap Tempo · OSC `/live/song/tap_tempo` */
  tapTempo(): void {
    const id: OscArg[] = [];
    this.p.send("/live/song/tap_tempo", [...id]);
  }

  /** Create an audio track (-1 = end) · OSC `/live/song/create_audio_track` */
  createAudioTrack(index: number): void {
    const id: OscArg[] = [];
    this.p.send("/live/song/create_audio_track", [...id, index]);
  }

  /** Create a MIDI track (-1 = end) · OSC `/live/song/create_midi_track` */
  createMidiTrack(index: number): void {
    const id: OscArg[] = [];
    this.p.send("/live/song/create_midi_track", [...id, index]);
  }

  /** Create a scene (-1 = end) · OSC `/live/song/create_scene` */
  createScene(index: number): void {
    const id: OscArg[] = [];
    this.p.send("/live/song/create_scene", [...id, index]);
  }

  /** Delete a scene · OSC `/live/song/delete_scene` */
  deleteScene(sceneIndex: number): void {
    const id: OscArg[] = [];
    this.p.send("/live/song/delete_scene", [...id, sceneIndex]);
  }

  /** Delete a track · OSC `/live/song/delete_track` */
  deleteTrack(trackIndex: number): void {
    const id: OscArg[] = [];
    this.p.send("/live/song/delete_track", [...id, trackIndex]);
  }

  /** Undo the last operation · OSC `/live/song/undo` */
  undo(): void {
    const id: OscArg[] = [];
    this.p.send("/live/song/undo", [...id]);
  }

  /** Redo the last undone operation · OSC `/live/song/redo` */
  redo(): void {
    const id: OscArg[] = [];
    this.p.send("/live/song/redo", [...id]);
  }

  /** Song tempo (BPM) · OSC `/live/song/{get,set}/tempo` */
  get tempo() {
    const p = this.p; const id: OscArg[] = [];
    return {
      get: (timeoutMs?: number): Promise<number> => p.query("/live/song/get/tempo", id, timeoutMs).then((a) => num(a, 0)),
      set: (v: number): void => p.send("/live/song/set/tempo", [...id, v]),
      subscribe: (cb: (v: number) => void): Subscription => p.subscribe("/live/song/start_listen/tempo", id, (a) => cb(num(a, 0))),
    };
  }

  /** Whether the song is playing · OSC `/live/song/{get,set}/is_playing` */
  get isPlaying() {
    const p = this.p; const id: OscArg[] = [];
    return {
      get: (timeoutMs?: number): Promise<boolean> => p.query("/live/song/get/is_playing", id, timeoutMs).then((a) => bool(a, 0)),
      subscribe: (cb: (v: boolean) => void): Subscription => p.subscribe("/live/song/start_listen/is_playing", id, (a) => cb(bool(a, 0))),
    };
  }

  /** Metronome on/off · OSC `/live/song/{get,set}/metronome` */
  get metronome() {
    const p = this.p; const id: OscArg[] = [];
    return {
      get: (timeoutMs?: number): Promise<boolean> => p.query("/live/song/get/metronome", id, timeoutMs).then((a) => bool(a, 0)),
      set: (v: boolean): void => p.send("/live/song/set/metronome", [...id, (v ? 1 : 0)]),
      subscribe: (cb: (v: boolean) => void): Subscription => p.subscribe("/live/song/start_listen/metronome", id, (a) => cb(bool(a, 0))),
    };
  }

  /** Whether the song is looping · OSC `/live/song/{get,set}/loop` */
  get loop() {
    const p = this.p; const id: OscArg[] = [];
    return {
      get: (timeoutMs?: number): Promise<boolean> => p.query("/live/song/get/loop", id, timeoutMs).then((a) => bool(a, 0)),
      set: (v: boolean): void => p.send("/live/song/set/loop", [...id, (v ? 1 : 0)]),
      subscribe: (cb: (v: boolean) => void): Subscription => p.subscribe("/live/song/start_listen/loop", id, (a) => cb(bool(a, 0))),
    };
  }

  /** Current song time, in beats · OSC `/live/song/{get,set}/current_song_time` */
  get currentSongTime() {
    const p = this.p; const id: OscArg[] = [];
    return {
      get: (timeoutMs?: number): Promise<number> => p.query("/live/song/get/current_song_time", id, timeoutMs).then((a) => num(a, 0)),
      set: (v: number): void => p.send("/live/song/set/current_song_time", [...id, v]),
      subscribe: (cb: (v: number) => void): Subscription => p.subscribe("/live/song/start_listen/current_song_time", id, (a) => cb(num(a, 0))),
    };
  }

  /** Time signature numerator · OSC `/live/song/{get,set}/signature_numerator` */
  get signatureNumerator() {
    const p = this.p; const id: OscArg[] = [];
    return {
      get: (timeoutMs?: number): Promise<number> => p.query("/live/song/get/signature_numerator", id, timeoutMs).then((a) => num(a, 0)),
      set: (v: number): void => p.send("/live/song/set/signature_numerator", [...id, v]),
      subscribe: (cb: (v: number) => void): Subscription => p.subscribe("/live/song/start_listen/signature_numerator", id, (a) => cb(num(a, 0))),
    };
  }

  /** Time signature denominator · OSC `/live/song/{get,set}/signature_denominator` */
  get signatureDenominator() {
    const p = this.p; const id: OscArg[] = [];
    return {
      get: (timeoutMs?: number): Promise<number> => p.query("/live/song/get/signature_denominator", id, timeoutMs).then((a) => num(a, 0)),
      set: (v: number): void => p.send("/live/song/set/signature_denominator", [...id, v]),
      subscribe: (cb: (v: number) => void): Subscription => p.subscribe("/live/song/start_listen/signature_denominator", id, (a) => cb(num(a, 0))),
    };
  }

  /** Current beat number (listen only) · OSC `/live/song/{get,set}/beat` */
  get beat() {
    const p = this.p; const id: OscArg[] = [];
    return {
      subscribe: (cb: (v: number) => void): Subscription => p.subscribe("/live/song/start_listen/beat", id, (a) => cb(num(a, 0))),
    };
  }

  /** Number of tracks · OSC `/live/song/{get,set}/num_tracks` */
  get numTracks() {
    const p = this.p; const id: OscArg[] = [];
    return {
      get: (timeoutMs?: number): Promise<number> => p.query("/live/song/get/num_tracks", id, timeoutMs).then((a) => num(a, 0)),
    };
  }

  /** Number of scenes · OSC `/live/song/{get,set}/num_scenes` */
  get numScenes() {
    const p = this.p; const id: OscArg[] = [];
    return {
      get: (timeoutMs?: number): Promise<number> => p.query("/live/song/get/num_scenes", id, timeoutMs).then((a) => num(a, 0)),
    };
  }

  /** All track names · OSC `/live/song/{get,set}/track_names` */
  get trackNames() {
    const p = this.p; const id: OscArg[] = [];
    return {
      get: (timeoutMs?: number): Promise<string[]> => p.query("/live/song/get/track_names", id, timeoutMs).then((a) => strs(a, 0)),
    };
  }
}

export class View {
  constructor(private p: VerbProvider) {}
  /** Selected scene index · OSC `/live/view/{get,set}/selected_scene` */
  get selectedScene() {
    const p = this.p; const id: OscArg[] = [];
    return {
      get: (timeoutMs?: number): Promise<number> => p.query("/live/view/get/selected_scene", id, timeoutMs).then((a) => num(a, 0)),
      set: (v: number): void => p.send("/live/view/set/selected_scene", [...id, v]),
      subscribe: (cb: (v: number) => void): Subscription => p.subscribe("/live/view/start_listen/selected_scene", id, (a) => cb(num(a, 0))),
    };
  }

  /** Selected track index · OSC `/live/view/{get,set}/selected_track` */
  get selectedTrack() {
    const p = this.p; const id: OscArg[] = [];
    return {
      get: (timeoutMs?: number): Promise<number> => p.query("/live/view/get/selected_track", id, timeoutMs).then((a) => num(a, 0)),
      set: (v: number): void => p.send("/live/view/set/selected_track", [...id, v]),
      subscribe: (cb: (v: number) => void): Subscription => p.subscribe("/live/view/start_listen/selected_track", id, (a) => cb(num(a, 0))),
    };
  }
}

export class Track {
  constructor(private p: VerbProvider, private trackId: number | string) {}
  /** Stop all clips on the track · OSC `/live/track/stop_all_clips` */
  stopAllClips(): void {
    const id: OscArg[] = [this.trackId];
    this.p.send("/live/track/stop_all_clips", [...id]);
  }

  /** clip clipId */
  clip(clipId: number): Clip {
    return new Clip(this.p, this.trackId, clipId);
  }

  /** clipSlot clipIndex */
  clipSlot(clipIndex: number): ClipSlot {
    return new ClipSlot(this.p, this.trackId, clipIndex);
  }

  /** device deviceId */
  device(deviceId: number): Device {
    return new Device(this.p, this.trackId, deviceId);
  }

  /** Track name · OSC `/live/track/{get,set}/name` */
  get name() {
    const p = this.p; const id: OscArg[] = [this.trackId];
    return {
      get: (timeoutMs?: number): Promise<string> => p.query("/live/track/get/name", id, timeoutMs).then((a) => str(a, 1)),
      set: (v: string): void => p.send("/live/track/set/name", [...id, v]),
      subscribe: (cb: (v: string) => void): Subscription => p.subscribe("/live/track/start_listen/name", id, (a) => cb(str(a, 1))),
    };
  }

  /** Track volume (0–1) · OSC `/live/track/{get,set}/volume` */
  get volume() {
    const p = this.p; const id: OscArg[] = [this.trackId];
    return {
      get: (timeoutMs?: number): Promise<number> => p.query("/live/track/get/volume", id, timeoutMs).then((a) => num(a, 1)),
      set: (v: number): void => p.send("/live/track/set/volume", [...id, v]),
      subscribe: (cb: (v: number) => void): Subscription => p.subscribe("/live/track/start_listen/volume", id, (a) => cb(num(a, 1))),
    };
  }

  /** Track panning (-1–1) · OSC `/live/track/{get,set}/panning` */
  get panning() {
    const p = this.p; const id: OscArg[] = [this.trackId];
    return {
      get: (timeoutMs?: number): Promise<number> => p.query("/live/track/get/panning", id, timeoutMs).then((a) => num(a, 1)),
      set: (v: number): void => p.send("/live/track/set/panning", [...id, v]),
      subscribe: (cb: (v: number) => void): Subscription => p.subscribe("/live/track/start_listen/panning", id, (a) => cb(num(a, 1))),
    };
  }

  /** Track mute · OSC `/live/track/{get,set}/mute` */
  get mute() {
    const p = this.p; const id: OscArg[] = [this.trackId];
    return {
      get: (timeoutMs?: number): Promise<boolean> => p.query("/live/track/get/mute", id, timeoutMs).then((a) => bool(a, 1)),
      set: (v: boolean): void => p.send("/live/track/set/mute", [...id, (v ? 1 : 0)]),
      subscribe: (cb: (v: boolean) => void): Subscription => p.subscribe("/live/track/start_listen/mute", id, (a) => cb(bool(a, 1))),
    };
  }

  /** Track solo · OSC `/live/track/{get,set}/solo` */
  get solo() {
    const p = this.p; const id: OscArg[] = [this.trackId];
    return {
      get: (timeoutMs?: number): Promise<boolean> => p.query("/live/track/get/solo", id, timeoutMs).then((a) => bool(a, 1)),
      set: (v: boolean): void => p.send("/live/track/set/solo", [...id, (v ? 1 : 0)]),
      subscribe: (cb: (v: boolean) => void): Subscription => p.subscribe("/live/track/start_listen/solo", id, (a) => cb(bool(a, 1))),
    };
  }

  /** Track arm · OSC `/live/track/{get,set}/arm` */
  get arm() {
    const p = this.p; const id: OscArg[] = [this.trackId];
    return {
      get: (timeoutMs?: number): Promise<boolean> => p.query("/live/track/get/arm", id, timeoutMs).then((a) => bool(a, 1)),
      set: (v: boolean): void => p.send("/live/track/set/arm", [...id, (v ? 1 : 0)]),
      subscribe: (cb: (v: boolean) => void): Subscription => p.subscribe("/live/track/start_listen/arm", id, (a) => cb(bool(a, 1))),
    };
  }

  /** Track color · OSC `/live/track/{get,set}/color` */
  get color() {
    const p = this.p; const id: OscArg[] = [this.trackId];
    return {
      get: (timeoutMs?: number): Promise<number> => p.query("/live/track/get/color", id, timeoutMs).then((a) => num(a, 1)),
      set: (v: number): void => p.send("/live/track/set/color", [...id, v]),
      subscribe: (cb: (v: number) => void): Subscription => p.subscribe("/live/track/start_listen/color", id, (a) => cb(num(a, 1))),
    };
  }

  /** Currently-playing slot index · OSC `/live/track/{get,set}/playing_slot_index` */
  get playingSlotIndex() {
    const p = this.p; const id: OscArg[] = [this.trackId];
    return {
      get: (timeoutMs?: number): Promise<number> => p.query("/live/track/get/playing_slot_index", id, timeoutMs).then((a) => num(a, 1)),
      subscribe: (cb: (v: number) => void): Subscription => p.subscribe("/live/track/start_listen/playing_slot_index", id, (a) => cb(num(a, 1))),
    };
  }

  /** Currently-fired slot index · OSC `/live/track/{get,set}/fired_slot_index` */
  get firedSlotIndex() {
    const p = this.p; const id: OscArg[] = [this.trackId];
    return {
      get: (timeoutMs?: number): Promise<number> => p.query("/live/track/get/fired_slot_index", id, timeoutMs).then((a) => num(a, 1)),
      subscribe: (cb: (v: number) => void): Subscription => p.subscribe("/live/track/start_listen/fired_slot_index", id, (a) => cb(num(a, 1))),
    };
  }

  /** Number of devices on the track · OSC `/live/track/{get,set}/num_devices` */
  get numDevices() {
    const p = this.p; const id: OscArg[] = [this.trackId];
    return {
      get: (timeoutMs?: number): Promise<number> => p.query("/live/track/get/num_devices", id, timeoutMs).then((a) => num(a, 1)),
    };
  }
}

export class Clip {
  constructor(private p: VerbProvider, private trackId: number | string, private clipId: number) {}
  /** Start clip playback · OSC `/live/clip/fire` */
  fire(): void {
    const id: OscArg[] = [this.trackId, this.clipId];
    this.p.send("/live/clip/fire", [...id]);
  }

  /** Stop clip playback · OSC `/live/clip/stop` */
  stop(): void {
    const id: OscArg[] = [this.trackId, this.clipId];
    this.p.send("/live/clip/stop", [...id]);
  }

  /** Clip name · OSC `/live/clip/{get,set}/name` */
  get name() {
    const p = this.p; const id: OscArg[] = [this.trackId, this.clipId];
    return {
      get: (timeoutMs?: number): Promise<string> => p.query("/live/clip/get/name", id, timeoutMs).then((a) => str(a, 2)),
      set: (v: string): void => p.send("/live/clip/set/name", [...id, v]),
    };
  }

  /** Clip color · OSC `/live/clip/{get,set}/color` */
  get color() {
    const p = this.p; const id: OscArg[] = [this.trackId, this.clipId];
    return {
      get: (timeoutMs?: number): Promise<number> => p.query("/live/clip/get/color", id, timeoutMs).then((a) => num(a, 2)),
      set: (v: number): void => p.send("/live/clip/set/color", [...id, v]),
    };
  }

  /** Clip length, in beats · OSC `/live/clip/{get,set}/length` */
  get length() {
    const p = this.p; const id: OscArg[] = [this.trackId, this.clipId];
    return {
      get: (timeoutMs?: number): Promise<number> => p.query("/live/clip/get/length", id, timeoutMs).then((a) => num(a, 2)),
    };
  }

  /** Whether the clip is playing · OSC `/live/clip/{get,set}/is_playing` */
  get isPlaying() {
    const p = this.p; const id: OscArg[] = [this.trackId, this.clipId];
    return {
      get: (timeoutMs?: number): Promise<boolean> => p.query("/live/clip/get/is_playing", id, timeoutMs).then((a) => bool(a, 2)),
    };
  }

  /** Whether the clip is recording · OSC `/live/clip/{get,set}/is_recording` */
  get isRecording() {
    const p = this.p; const id: OscArg[] = [this.trackId, this.clipId];
    return {
      get: (timeoutMs?: number): Promise<boolean> => p.query("/live/clip/get/is_recording", id, timeoutMs).then((a) => bool(a, 2)),
    };
  }

  /** Clip gain · OSC `/live/clip/{get,set}/gain` */
  get gain() {
    const p = this.p; const id: OscArg[] = [this.trackId, this.clipId];
    return {
      get: (timeoutMs?: number): Promise<number> => p.query("/live/clip/get/gain", id, timeoutMs).then((a) => num(a, 2)),
      set: (v: number): void => p.send("/live/clip/set/gain", [...id, v]),
    };
  }

  /** Coarse re-pitch (semitones) · OSC `/live/clip/{get,set}/pitch_coarse` */
  get pitchCoarse() {
    const p = this.p; const id: OscArg[] = [this.trackId, this.clipId];
    return {
      get: (timeoutMs?: number): Promise<number> => p.query("/live/clip/get/pitch_coarse", id, timeoutMs).then((a) => num(a, 2)),
      set: (v: number): void => p.send("/live/clip/set/pitch_coarse", [...id, v]),
    };
  }

  /** Clip muted state · OSC `/live/clip/{get,set}/muted` */
  get muted() {
    const p = this.p; const id: OscArg[] = [this.trackId, this.clipId];
    return {
      get: (timeoutMs?: number): Promise<boolean> => p.query("/live/clip/get/muted", id, timeoutMs).then((a) => bool(a, 2)),
      set: (v: boolean): void => p.send("/live/clip/set/muted", [...id, (v ? 1 : 0)]),
    };
  }

  /** Clip playing position · OSC `/live/clip/{get,set}/playing_position` */
  get playingPosition() {
    const p = this.p; const id: OscArg[] = [this.trackId, this.clipId];
    return {
      get: (timeoutMs?: number): Promise<number> => p.query("/live/clip/get/playing_position", id, timeoutMs).then((a) => num(a, 2)),
      subscribe: (cb: (v: number) => void): Subscription => p.subscribe("/live/clip/start_listen/playing_position", id, (a) => cb(num(a, 2))),
    };
  }
}

export class ClipSlot {
  constructor(private p: VerbProvider, private trackIndex: number | string, private clipIndex: number) {}
  /** Fire play/pause of the clip slot · OSC `/live/clip_slot/fire` */
  fire(): void {
    const id: OscArg[] = [this.trackIndex, this.clipIndex];
    this.p.send("/live/clip_slot/fire", [...id]);
  }

  /** Create a clip in the slot · OSC `/live/clip_slot/create_clip` */
  createClip(length: number): void {
    const id: OscArg[] = [this.trackIndex, this.clipIndex];
    this.p.send("/live/clip_slot/create_clip", [...id, length]);
  }

  /** Delete the clip in the slot · OSC `/live/clip_slot/delete_clip` */
  deleteClip(): void {
    const id: OscArg[] = [this.trackIndex, this.clipIndex];
    this.p.send("/live/clip_slot/delete_clip", [...id]);
  }

  /** Whether the slot has a clip · OSC `/live/clip_slot/{get,set}/has_clip` */
  get hasClip() {
    const p = this.p; const id: OscArg[] = [this.trackIndex, this.clipIndex];
    return {
      get: (timeoutMs?: number): Promise<boolean> => p.query("/live/clip_slot/get/has_clip", id, timeoutMs).then((a) => bool(a, 2)),
    };
  }
}

export class Scene {
  constructor(private p: VerbProvider, private sceneId: number) {}
  /** Trigger the scene · OSC `/live/scene/fire` */
  fire(): void {
    const id: OscArg[] = [this.sceneId];
    this.p.send("/live/scene/fire", [...id]);
  }

  /** Scene name · OSC `/live/scene/{get,set}/name` */
  get name() {
    const p = this.p; const id: OscArg[] = [this.sceneId];
    return {
      get: (timeoutMs?: number): Promise<string> => p.query("/live/scene/get/name", id, timeoutMs).then((a) => str(a, 1)),
      set: (v: string): void => p.send("/live/scene/set/name", [...id, v]),
    };
  }

  /** Scene color · OSC `/live/scene/{get,set}/color` */
  get color() {
    const p = this.p; const id: OscArg[] = [this.sceneId];
    return {
      get: (timeoutMs?: number): Promise<number> => p.query("/live/scene/get/color", id, timeoutMs).then((a) => num(a, 1)),
      set: (v: number): void => p.send("/live/scene/set/color", [...id, v]),
    };
  }

  /** Whether the scene is empty · OSC `/live/scene/{get,set}/is_empty` */
  get isEmpty() {
    const p = this.p; const id: OscArg[] = [this.sceneId];
    return {
      get: (timeoutMs?: number): Promise<boolean> => p.query("/live/scene/get/is_empty", id, timeoutMs).then((a) => bool(a, 1)),
    };
  }

  /** Whether the scene is triggered · OSC `/live/scene/{get,set}/is_triggered` */
  get isTriggered() {
    const p = this.p; const id: OscArg[] = [this.sceneId];
    return {
      get: (timeoutMs?: number): Promise<boolean> => p.query("/live/scene/get/is_triggered", id, timeoutMs).then((a) => bool(a, 1)),
    };
  }

  /** Scene tempo · OSC `/live/scene/{get,set}/tempo` */
  get tempo() {
    const p = this.p; const id: OscArg[] = [this.sceneId];
    return {
      get: (timeoutMs?: number): Promise<number> => p.query("/live/scene/get/tempo", id, timeoutMs).then((a) => num(a, 1)),
      set: (v: number): void => p.send("/live/scene/set/tempo", [...id, v]),
    };
  }
}

export class Device {
  constructor(private p: VerbProvider, private trackId: number | string, private deviceId: number) {}
  /** deviceParameter parameterId */
  parameter(parameterId: number): DeviceParameter {
    return new DeviceParameter(this.p, this.trackId, this.deviceId, parameterId);
  }

  /** Device name · OSC `/live/device/{get,set}/name` */
  get name() {
    const p = this.p; const id: OscArg[] = [this.trackId, this.deviceId];
    return {
      get: (timeoutMs?: number): Promise<string> => p.query("/live/device/get/name", id, timeoutMs).then((a) => str(a, 2)),
    };
  }

  /** Device class name (e.g. Operator) · OSC `/live/device/{get,set}/class_name` */
  get className() {
    const p = this.p; const id: OscArg[] = [this.trackId, this.deviceId];
    return {
      get: (timeoutMs?: number): Promise<string> => p.query("/live/device/get/class_name", id, timeoutMs).then((a) => str(a, 2)),
    };
  }

  /** 1=audio_effect, 2=instrument, 4=midi_effect · OSC `/live/device/{get,set}/type` */
  get type() {
    const p = this.p; const id: OscArg[] = [this.trackId, this.deviceId];
    return {
      get: (timeoutMs?: number): Promise<number> => p.query("/live/device/get/type", id, timeoutMs).then((a) => num(a, 2)),
    };
  }

  /** Number of parameters · OSC `/live/device/{get,set}/num_parameters` */
  get numParameters() {
    const p = this.p; const id: OscArg[] = [this.trackId, this.deviceId];
    return {
      get: (timeoutMs?: number): Promise<number> => p.query("/live/device/get/num_parameters", id, timeoutMs).then((a) => num(a, 2)),
    };
  }

  /** All parameter names · OSC `/live/device/{get,set}/parameters/name` */
  get parametersName() {
    const p = this.p; const id: OscArg[] = [this.trackId, this.deviceId];
    return {
      get: (timeoutMs?: number): Promise<string[]> => p.query("/live/device/get/parameters/name", id, timeoutMs).then((a) => strs(a, 2)),
    };
  }

  /** All parameter values · OSC `/live/device/{get,set}/parameters/value` */
  get parametersValue() {
    const p = this.p; const id: OscArg[] = [this.trackId, this.deviceId];
    return {
      get: (timeoutMs?: number): Promise<number[]> => p.query("/live/device/get/parameters/value", id, timeoutMs).then((a) => nums(a, 2)),
    };
  }
}

export class DeviceParameter {
  constructor(private p: VerbProvider, private trackId: number | string, private deviceId: number, private parameterId: number) {}
  /** Parameter value · OSC `/live/device/{get,set}/parameter/value` */
  get value() {
    const p = this.p; const id: OscArg[] = [this.trackId, this.deviceId, this.parameterId];
    return {
      get: (timeoutMs?: number): Promise<number> => p.query("/live/device/get/parameter/value", id, timeoutMs).then((a) => num(a, 3)),
      set: (v: number): void => p.send("/live/device/set/parameter/value", [...id, v]),
      subscribe: (cb: (v: number) => void): Subscription => p.subscribe("/live/device/start_listen/parameter/value", id, (a) => cb(num(a, 3))),
    };
  }

  /** Parameter value as a readable string · OSC `/live/device/{get,set}/parameter/value_string` */
  get valueString() {
    const p = this.p; const id: OscArg[] = [this.trackId, this.deviceId, this.parameterId];
    return {
      get: (timeoutMs?: number): Promise<string> => p.query("/live/device/get/parameter/value_string", id, timeoutMs).then((a) => str(a, 3)),
    };
  }
}

export class Live {
  readonly song: Song;
  readonly view: View;
  readonly application: Application;
  constructor(private p: VerbProvider) {
    this.song = new Song(p);
    this.view = new View(p);
    this.application = new Application(p);
  }
  track(trackId: number | string): Track { return new Track(this.p, trackId); }
  scene(sceneId: number): Scene { return new Scene(this.p, sceneId); }
  clipSlot(trackIndex: number, clipIndex: number): ClipSlot { return new ClipSlot(this.p, trackIndex, clipIndex); }
  get master(): Track { return new Track(this.p, "master"); }
  returnTrack(prefix: string): Track { return new Track(this.p, prefix); }
  readonly raw = {
    send: (address: string, args?: OscArg[]): void => this.p.send(address, args),
    query: (address: string, args?: OscArg[], timeoutMs?: number): Promise<OscArg[]> => this.p.query(address, args, timeoutMs),
    subscribe: (address: string, args: OscArg[], cb: (args: OscArg[]) => void): Subscription => this.p.subscribe(address, args, cb),
  };
}
